trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan'  # Managed node pool name

variables:
  services: "adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice shoppingassistantservice"
  sonarHost: "http://54.82.85.241:9000/"
  sonarToken: "squ_80c52fbbe68721fce9eb901fc1ae78fe23d78dcf"  # Replace with your SonarQube token

stages:
  - stage: SonarQubeSetup
    displayName: 'SonarQube Project Setup'
    jobs:
      - job: CreateProjects
        displayName: 'Create SonarQube Projects'
        steps:
          - script: |
              for service in $(services); do
                echo "Creating SonarQube project for $service..."
                curl -u "admin:${{ variables.sonarToken }}" -X POST "${{ variables.sonarHost }}/api/projects/create" -d "project=${service}&name=${service}"

                echo "Scanning $service with SonarQube..."
                sonar-scanner -Dproject.settings=$service/sonar-project.properties
              done
            displayName: 'Create SonarQube Projects and Run Scans'
