trigger:
  branches:
    include:
      - azure-pipelines

pr:
  branches:
    include:
      - azure-pipelines

pool:
  name: 'Chandan'  # Managed node pool name

variables:
  services: "adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice shoppingassistantservice"
  sonarHost: "http://54.82.85.241:9000/"
  sonarToken: "squ_80c52fbbe68721fce9eb901fc1ae78fe23d78dcf"  # Replace with your SonarQube token

stages:
  - stage: SonarQubeSetup
    displayName: 'SonarQube Project Setup'
    jobs:
      - job: CreateProjects
        displayName: 'Create SonarQube Projects'
        strategy:
          matrix:
            adservice: {}
            cartservice: {}
            checkoutservice: {}
            currencyservice: {}
            emailservice: {}
            frontend: {}
            loadgenerator: {}
            paymentservice: {}
            productcatalogservice: {}
            recommendationservice: {}
            shippingservice: {}
            shoppingassistantservice: {}
        steps:
          - task: SonarQubePrepare@6
            inputs:
              SonarQube: 'sonar'  # Replace with your SonarQube service connection name
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: '$(service)'  # Use the service name from the matrix
              cliProjectName: '$(service)'
              cliSources: '.'
              extraProperties: |
                sonar.java.binaries=.  # Adjust as necessary for your project structure

          - task: SonarQubeAnalyze@6
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'  # Specify the JDK version you are using
